CREATE TABLE IF NOT EXISTS "comm_chats" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "comm_chats_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"tgId" integer NOT NULL,
	"username" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "tgUsers" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tgUsers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"tgID" integer,
	"refID" text,
	"referrerID" text,
	"isBot" boolean DEFAULT true,
	"firstName" text NOT NULL,
	"lastName" text,
	"username" text,
	"languageCode" text,
	"groupChatStatus" text,
	"joinReqSent" boolean DEFAULT false,
	CONSTRAINT "tgUsers_tgID_unique" UNIQUE("tgID"),
	CONSTRAINT "tgUsers_refID_unique" UNIQUE("refID")
);
